version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rede_local

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: senha123
      DB_NAME: meubanco
    depends_on:
      - db
    networks:
      - rede_local

networks:
  rede_local:

volumes:
  db_data:
